- name: Deploy application
  hosts: all
  become: true
  roles:
  # Set path to role because packer list default Settings
    - { role: '../roles/app' }
  # tasks:
  #   - name: Install ruby and Bundler
  #     apt:
  #       name: "{{ item }}"
  #       state: present
  #     with_items:
  #       - ruby-full
  #       - ruby-bundler
  #       - build-essential
